#!/usr/bin/env python3
"""
ArchGen — Architecture Documentation Generator for Notes.ai.

Usage:
    python -m archgen.main [--output-dir ./docs]

Generates a complete architecture summary across all surfaces.
"""

import os
import argparse
import datetime
import inspect

from .core import SystemArchitecture, DeploymentBoundaries
from .backend import FlaskAPI, RelayServer, DatabaseSchema, DatabaseScripts
from .ios import (
    WorkspaceModel, NotebookModel, PageModel,
    NoteImageModel, NoteTextModel, AudioObjectModel,
    ShapeObjectModel, TableObjectModel, BrowserObjectModel,
    AIChatSessionModel, AIChatMessageModel, AIProviderModel,
    ProviderTypeEnum,
    SyncManager, AuthService as iOSAuthService, AIService,
    AIProviderStore, AudioRecorder, DrawingSettings,
    SecurityService, TranscriptionService,
    VIEW_REGISTRY, MODEL_HIERARCHY,
)
from .frontend import (
    LockScreen, Sidebar, PageGrid, AIPanel,
    Navbar, TrafficMonitor, AppShell, SettingsPanel,
    INDEX_HTML_CONFIG,
)
from .data_flow import (
    SyncCycleFlow, ReadAPIFlow, AuthFlow, AIChatFlow,
    SnapshotDownloadFlow, DATA_FLOW_DIAGRAM,
)
from .diagrams import (
    system_context_diagram,
    ios_container_diagram,
    backend_container_diagram,
    frontend_container_diagram,
    sync_sequence_diagram,
    deployment_diagram,
    model_hierarchy_diagram,
)

PREAMBLE = """# Notes.ai — System Architecture Documentation

> Generated by `archgen` — an abstract, non-proprietary description of
> the system's components, responsibilities, and data flows.

**Date:** {date}
**Version:** 2.0.0

---


"""


def render_module_docstring(cls) -> str:
    """Extract class docstring as module description."""
    doc = inspect.getdoc(cls)
    if not doc:
        return ""
    lines = doc.strip().split("\n")
    title = lines[0].strip()
    body = "\n".join(lines[1:]).strip()
    return f"### {title}\n\n{body}\n\n---\n\n"


def render_model_summary(name: str, doc: str) -> str:
    """Render a model class summary."""
    return f"### {name}\n\n{doc}\n\n---\n\n"


def generate(output_dir: str) -> None:
    """Generate all architecture documentation files."""
    os.makedirs(output_dir, exist_ok=True)

    lines = [PREAMBLE.format(date=datetime.date.today().isoformat())]

    # 1. System Overview
    lines.append("## 1. System Overview\n")
    lines.append(SystemArchitecture.describe())
    lines.append("---\n")

    # 2. Deployment Boundaries
    lines.append("## 2. Deployment Boundaries\n")
    for surface, config in DeploymentBoundaries.BOUNDARIES.items():
        lines.append(f"### {surface.title()}\n")
        for key, value in config.items():
            if isinstance(value, list):
                lines.append(f"- **{key.replace('_', ' ').title()}:** {', '.join(map(str, value))}")
            elif isinstance(value, dict):
                lines.append(f"- **{key.replace('_', ' ').title()}:**")
                for k, v in value.items():
                    lines.append(f"  - {k}: {v}")
            else:
                lines.append(f"- **{key.replace('_', ' ').title()}:** {value}")
        lines.append("")
    lines.append("---\n")

    # 3. Backend
    lines.append("## 3. Backend Modules\n")
    for cls in [FlaskAPI, RelayServer, DatabaseSchema, DatabaseScripts]:
        lines.append(render_module_docstring(cls))
    lines.append("### Backend Architecture Diagram\n")
    lines.append(backend_container_diagram())
    lines.append("---\n")

    # 4. iOS
    lines.append("## 4. iOS App Modules\n")

    lines.append("### 4a. SwiftData Models\n")
    for name, cls in [
        ("Workspace", WorkspaceModel),
        ("Notebook", NotebookModel),
        ("Page", PageModel),
        ("NoteImage", NoteImageModel),
        ("NoteText", NoteTextModel),
        ("AudioObject", AudioObjectModel),
        ("ShapeObject", ShapeObjectModel),
        ("TableObject", TableObjectModel),
        ("BrowserObject", BrowserObjectModel),
        ("AIChatSession", AIChatSessionModel),
        ("AIChatMessage", AIChatMessageModel),
        ("AIProvider", AIProviderModel),
        ("ProviderType", ProviderTypeEnum),
    ]:
        lines.append(render_module_docstring(cls))

    lines.append("### Model Hierarchy\n")
    lines.append(f"```\n{MODEL_HIERARCHY}\n```\n")

    lines.append("### 4b. Services Layer\n")
    for cls in [SyncManager, iOSAuthService, AIService, AIProviderStore,
                AudioRecorder, DrawingSettings, SecurityService, TranscriptionService]:
        lines.append(render_module_docstring(cls))

    lines.append("### 4c. SwiftUI Views\n")
    for group, views in VIEW_REGISTRY.items():
        lines.append(f"**{group.replace('_', ' ').title()}:**\n")
        for v in views:
            lines.append(f"- {v}")
        lines.append("")

    lines.append("### iOS Architecture Diagram\n")
    lines.append(ios_container_diagram())
    lines.append("---\n")

    # 5. Frontend
    lines.append("## 5. Web Frontend Modules\n")
    for cls in [LockScreen, Sidebar, PageGrid, AIPanel, Navbar,
                TrafficMonitor, AppShell, SettingsPanel]:
        lines.append(render_module_docstring(cls))
    lines.append("### Frontend Architecture Diagram\n")
    lines.append(frontend_container_diagram())
    lines.append("---\n")

    # 6. Data Flows
    lines.append("## 6. End-to-End Data Flows\n")
    lines.append(DATA_FLOW_DIAGRAM)
    lines.append("\n")
    for flow_cls in [SyncCycleFlow, ReadAPIFlow, AuthFlow, AIChatFlow, SnapshotDownloadFlow]:
        lines.append(render_module_docstring(flow_cls))
    lines.append("### Sync Sequence Diagram\n")
    lines.append(sync_sequence_diagram())
    lines.append("---\n")

    # 7. Diagrams
    lines.append("## 7. Architecture Diagrams\n")
    lines.append(system_context_diagram())
    lines.append(model_hierarchy_diagram())
    lines.append(deployment_diagram())

    # Write the single-file summary
    index_path = os.path.join(output_dir, "SYSTEM_ARCHITECTURE.md")
    with open(index_path, "w") as f:
        f.writelines(lines)
    print(f"✅ Generated: {index_path}")

    # Generate per-surface docs
    _generate_surface_doc(
        output_dir, "backend", "## Backend Architecture\n",
        [FlaskAPI, RelayServer, DatabaseSchema, DatabaseScripts],
        backend_container_diagram(),
    )
    _generate_surface_doc_ios(output_dir)
    _generate_surface_doc(
        output_dir, "frontend", "## Web Frontend Architecture\n",
        [LockScreen, Sidebar, PageGrid, AIPanel, Navbar,
         TrafficMonitor, AppShell, SettingsPanel],
        frontend_container_diagram(),
    )

    print(f"\n✅ All docs generated in: {output_dir}")
    print(f"   Open: {index_path}")


def _generate_surface_doc(output_dir: str, name: str, header: str,
                          classes: list, diagram: str) -> None:
    """Generate a per-surface markdown file."""
    lines = [
        f"# Notes.ai — {name.title()} Architecture\n\n",
        f"_{datetime.date.today().isoformat()}_\n\n---\n\n",
        header,
    ]
    for cls in classes:
        lines.append(render_module_docstring(cls))
    lines.append("### Architecture Diagram\n")
    lines.append(diagram)

    path = os.path.join(output_dir, f"{name.upper()}_ARCHITECTURE.md")
    with open(path, "w") as f:
        f.writelines(lines)
    print(f"   📄 {path}")


def _generate_surface_doc_ios(output_dir: str) -> None:
    """Generate the iOS architecture doc with models + services + views."""
    name = "ios"
    lines = [
        f"# Notes.ai — iOS App Architecture\n\n",
        f"_{datetime.date.today().isoformat()}_\n\n---\n\n",
        "## iOS Architecture\n\n",
    ]

    lines.append("### SwiftData Models\n")
    for label, cls in [
        ("Workspace", WorkspaceModel),
        ("Notebook", NotebookModel),
        ("Page", PageModel),
        ("NoteImage", NoteImageModel),
        ("NoteText", NoteTextModel),
        ("AudioObject", AudioObjectModel),
        ("ShapeObject", ShapeObjectModel),
        ("TableObject", TableObjectModel),
        ("BrowserObject", BrowserObjectModel),
        ("AIChatSession", AIChatSessionModel),
        ("AIChatMessage", AIChatMessageModel),
        ("AIProvider", AIProviderModel),
        ("ProviderType", ProviderTypeEnum),
    ]:
        lines.append(render_module_docstring(cls))

    lines.append(f"```\n{MODEL_HIERARCHY}\n```\n\n")

    lines.append("### Services Layer\n")
    for cls in [SyncManager, iOSAuthService, AIService, AIProviderStore,
                AudioRecorder, DrawingSettings, SecurityService, TranscriptionService]:
        lines.append(render_module_docstring(cls))

    lines.append("### SwiftUI Views\n")
    for group, views in VIEW_REGISTRY.items():
        lines.append(f"**{group.replace('_', ' ').title()}:**\n")
        for v in views:
            lines.append(f"- {v}")
        lines.append("")

    lines.append("### Architecture Diagram\n")
    lines.append(ios_container_diagram())

    path = os.path.join(output_dir, f"{name.upper()}_ARCHITECTURE.md")
    with open(path, "w") as f:
        f.writelines(lines)
    print(f"   📄 {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Notes.ai architecture docs")
    parser.add_argument(
        "--output-dir",
        default="./docs/architecture",
        help="Output directory for generated docs (default: ./docs/architecture)",
    )
    args = parser.parse_args()
    generate(args.output_dir)


if __name__ == "__main__":
    main()
